# Site settings
title: Project Black IO
email: jvschin@gmail.com
description: The ramblings of a developer/security enthusiast
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://projectblack.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown

# sass settings
sass:
    sass_dir: _sass
